spring.application.name=CarLoacation

server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:carrentaldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=badr
spring.datasource.password=badr
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Springdoc / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
